[package]
name = "decimals"
version = "0.1.2"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["David Skyberg <davidskyberg@gmail.com>"]
description = "A Rust library for rounding to a number of decimal places"
repository = "https://github.com/dskyberg/decimals"
readme = "README.md"
